name: CI (MAMEUI)

on: [push, pull_request]

jobs:

  build-windows-gcc:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        install: git make mingw-w64-x86_64-gcc mingw-w64-x86_64-python mingw-w64-x86_64-lld mingw-w64-x86_64-libc++
    - uses: actions/checkout@master
    - name: Build
      env:
        MINGW64: "/mingw64"
        OSD: "messui"
        PTR64: "1"
      run: make -j2
    - name: Validate
      run: ./mameui -validate
    - uses: actions/upload-artifact@master
      with:
        name: mameui-windows-gcc-${{ github.sha }}
        path: mameui.exe
